if(IDF_TARGET STREQUAL "linux")
    idf_component_register(
        SRCS
            "src/hal_gpio.cpp"
            "src/hal_timer.cpp"
            "src/hal_sys_rom.cpp"
            "src/hal_nvs.cpp"
            "src/hal_system.cpp"
            "src/hal_pcnt.cpp"
            "src/hal_system_time.cpp"
        INCLUDE_DIRS
            "include"
            "include/interfaces"
        REQUIRES
            esp_timer
            driver
            nvs_flash
            esp_netif
            esp_app_format
    )
else()
    idf_component_register(
        SRCS
            "src/hal_gpio.cpp"
            "src/hal_timer.cpp"
            "src/hal_sys_rom.cpp"
            "src/hal_nvs.cpp"
            "src/hal_sleep.cpp"
            "src/hal_adc_calibration.cpp"
            "src/hal_adc_oneshot.cpp"
            "src/hal_freertos.cpp"
            "src/hal_system.cpp"
            "src/hal_touch.cpp"
            "src/hal_pcnt.cpp"
            "src/hal_system_time.cpp"
            "src/hal_sntp.cpp"
        INCLUDE_DIRS
            "include"
            "include/interfaces"
        REQUIRES
            esp_timer
            driver
            esp_adc
            nvs_flash
            esp_driver_touch_sens
            esp_driver_pcnt
            esp_netif
            esp_app_format
    )
endif()
